# Generated by Django 4.2 on 2024-06-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_habilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='link_repositorio',
        ),
    ]
