# Generated by Django 4.2 on 2024-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_proyecto_contenido_alter_contacto_mensaje_cifrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link_repositorio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
